name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      VITE_CONVEX_URL: ${{ secrets.VITE_CONVEX_URL }}

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: "Optional: Lint prüfen"
        run: npm run lint
        continue-on-error: true  # Wenn kein Linter vorhanden, kann diese Zeile entfernt werden

      - name: Build ausführen
        run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/**"
          target: ${{ secrets.TARGET_PATH }}
          strip_components: 1
